import { mat_button_type } from "../enums/mat-button-type-enum"

export const mat_button_tokens: mat_button_token[] = [
    {
        "type": mat_button_type.BASIC,
        "tokens": [
            "--text-container-shape: 12px;",
            "--text-label-text-color: #ba005c;",
            "--text-disabled-label-text-color: #a0a0a0;",
            "--text-label-text-font: Arial;",
            "--text-label-text-size: 16px;",
            "--text-label-text-tracking: 0.05em;",
            "--text-label-text-weight: 400;",
            "--text-label-text-transform: none;",
            "--text-container-height: 40px;",
            "--text-horizontal-padding: 12px;",
            "--text-with-icon-horizontal-padding: 12px;",
            "--text-icon-spacing: 5px;",
            "--text-icon-offset: 5px;",
            "--text-state-layer-color: #ba005c;",
            "--text-disabled-state-layer-color: #a0a0a0;",
            "--text-ripple-color: #ba005c;",
            "--text-hover-state-layer-opacity: 0.08;",
            "--text-focus-state-layer-opacity: 0.12;",
            "--text-pressed-state-layer-opacity: 0.16;",
            "--text-touch-target-display: 48px;",
        ]
    },
    {
        "type": mat_button_type.RAISED,
        "tokens": [
            "--protected-container-shape: 8px;",
            "--protected-container-elevation-shadow: none;",
            "--protected-disabled-container-elevation-shadow: none;",
            "--protected-focus-container-elevation-shadow: none;",
            "--protected-hover-container-elevation-shadow: none;",
            "--protected-pressed-container-elevation-shadow: none;",
            "--protected-container-color: #f5f5f5;",
            "--protected-label-text-color: #007acc;",
            "--protected-disabled-container-color: #d0d0d0;",
            "--protected-disabled-label-text-color: #808080;",
            "--protected-label-text-font: 'Roboto', sans-serif;",
            "--protected-label-text-size: 14px;",
            "--protected-label-text-tracking: 0.04em;",
            "--protected-label-text-weight: 500;",
            "--protected-label-text-transform: uppercase;",
            "--protected-container-height: 48px;",
            "--protected-horizontal-padding: 16px;",
            "--protected-icon-spacing: 8px;",
            "--protected-icon-offset: 4px;",
            "--protected-state-layer-color: #0055aa;",
            "--protected-disabled-state-layer-color: #a5a5a5;",
            "--protected-ripple-color: #003366;",
            "--protected-hover-state-layer-opacity: 0.08;",
            "--protected-focus-state-layer-opacity: 0.12;",
            "--protected-pressed-state-layer-opacity: 0.16;"
        ]
    },
    {
        "type": mat_button_type.STROKED,
        "tokens": [
            " --outlined-outline-width: 2px;",
            " --outlined-container-shape: 8px;",
            " --outlined-disabled-outline-color: #a5a5a5;",
            " --outlined-disabled-label-text-color: #808080;",
            " --outlined-label-text-color: #007acc;",
            " --outlined-outline-color: #0055aa;",
            " --outlined-label-text-font: 'Roboto';",
            " --outlined-label-text-size: 14px;",
            " --outlined-label-text-tracking: 0.04em;",
            " --outlined-label-text-weight: 500;",
            " --outlined-label-text-transform: uppercase;",
            " --outlined-container-height: 48px;",
            " --outlined-horizontal-padding: 16px;",
            " --outlined-icon-spacing: 8px;",
            " --outlined-icon-offset: 4px;",
            " --outlined-state-layer-color: #0055aa;",
            " --outlined-disabled-state-layer-color: #a5a5a5;",
            " --outlined-ripple-color: #003366;",
            " --outlined-hover-state-layer-opacity: 0.08;",
            " --outlined-focus-state-layer-opacity: 0.12;",
            " --outlined-pressed-state-layer-opacity: 0.16;",
        ]
    },
    {
        "type": mat_button_type.FLAT,
        "tokens": [
            "--filled-container-shape: 8px;",
            "--filled-container-color: #007acc;",
            "--filled-label-text-color: #ffffff;",
            "--filled-disabled-container-color: #d0d0d0;",
            "--filled-disabled-label-text-color: #808080;",
            "--filled-label-text-font: 'Roboto', sans-serif;",
            "--filled-label-text-size: 14px;",
            "--filled-label-text-tracking: 0.04em;",
            "--filled-label-text-weight: 500;",
            "--filled-label-text-transform: uppercase;",
            "--filled-container-height: 48px;",
            "--filled-horizontal-padding: 16px;",
            "--filled-icon-spacing: 8px;",
            "--filled-icon-offset: 4px;",
            "--filled-state-layer-color: #ffffff;",
            "--filled-disabled-state-layer-color: #a5a5a5;",
            "--filled-ripple-color: #ffffff;",
            "--filled-hover-state-layer-opacity: 0.08;",
            "--filled-focus-state-layer-opacity: 0.12;",
            "--filled-pressed-state-layer-opacity: 0.16;"
        ]
    },
    {
        "type": mat_button_type.ICON,
        "tokens": [
            "--icon-size: 24px;",
            "--icon-color: #5f6368;",
            "--disabled-icon-color: #a5a5a5;",
            "--state-layer-size: 32px;",
            "--state-layer-color: #5f6368;",
            "--disabled-state-layer-color: #a5a5a5;",
            "--ripple-color: #5f6368;",
            "--hover-state-layer-opacity: 0.08;",
            "--focus-state-layer-opacity: 0.12;",
            "--pressed-state-layer-opacity: 0.16;"
        ]
    },
    {
        "type": mat_button_type.FAB,
        "tokens": [
            "--fab-container-shape: 50%;",
            "--fab-container-elevation-shadow: none;",
            "--fab-focus-container-elevation-shadow: none;",
            "--fab-hover-container-elevation-shadow: none;",
            "--fab-pressed-container-elevation-shadow: none;",
            "--fab-container-color: #6200ea;",
            "--fab-foreground-color: #ffffff;",
            "--fab-state-layer-color: #ffffff;",
            "--fab-disabled-state-container-color: #bdbdbd;",
            "--fab-disabled-state-foreground-color: #757575;",
            "--fab-disabled-state-layer-color: none;",
            "--fab-ripple-color: #ffffff;",
            "--fab-hover-state-layer-opacity: 0.08;",
            "--fab-focus-state-layer-opacity: 0.12;",
            "--fab-pressed-state-layer-opacity: 0.16;",
            "--fab-touch-target-display: 56px;"
        ]
    },
    {
        "type": mat_button_type.MINIFAB,
        "tokens": [
            "--small-fab-container-shape: 50%;",
            "--small-fab-container-elevation-shadow: none;",
            "--small-fab-focus-container-elevation-shadow: none;",
            "--small-fab-hover-container-elevation-shadow: none;",
            "--small-fab-pressed-container-elevation-shadow: none;",
            "--small-fab-container-color: #6200ea;",
            "--small-fab-foreground-color: #ffffff;",
            "--small-fab-state-layer-color: #ffffff;",
            "--small-fab-disabled-state-container-color: #bdbdbd;",
            "--small-fab-disabled-state-foreground-color: #757575;",
            "--small-fab-disabled-state-layer-color: none;",
            "--small-fab-ripple-color: #ffffff;",
            "--small-fab-hover-state-layer-opacity: 0.08;",
            "--small-fab-focus-state-layer-opacity: 0.12;",
            "--small-fab-pressed-state-layer-opacity: 0.16;",
            "--small-fab-touch-target-display: 40px;",
        ]
    },
    {
        "type": mat_button_type.ExtendedFAB,
        "tokens": [
            "--extended-fab-container-shape: 28px;",
            "--extended-fab-container-elevation-shadow: none;",
            "--extended-fab-focus-container-elevation-shadow: none;",
            "--extended-fab-hover-container-elevation-shadow: none;",
            "--extended-fab-pressed-container-elevation-shadow: none;",
            "--extended-fab-container-color: #6200ea;",
            "--extended-fab-foreground-color: #ffffff;",
            "--extended-fab-state-layer-color: #ffffff;",
            "--extended-fab-disabled-state-container-color: #bdbdbd;",
            "--extended-fab-disabled-state-foreground-color: #757575;",
            "--extended-fab-disabled-state-layer-color: none;",
            "--extended-fab-ripple-color: #ffffff;",
            "--extended-fab-hover-state-layer-opacity: 0.08;",
            "--extended-fab-focus-state-layer-opacity: 0.12;",
            "--extended-fab-pressed-state-layer-opacity: 0.16;",
            "--extended-fab-touch-target-display: 48px;",
            "--extended-fab-label-text-font: 'Roboto', sans-serif;",
            "--extended-fab-label-text-size: 14px;",
            "--extended-fab-label-text-tracking: 0.04em;",
            "--extended-fab-label-text-weight: 500;",
        ]
    }
]

export interface mat_button_token {
    "type": string,
    "tokens": string[]
}